# Generated by Django 4.0.3 on 2022-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
