# Generated by Django 4.0.3 on 2022-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='destinations', to='tags.tag'),
        ),
    ]
