# Generated by Django 4.0.3 on 2022-03-07 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0002_alter_continent_image_alter_continent_name'),
        ('tags', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='continents.continent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='tag',
            field=models.ManyToManyField(related_name='destinations', to='tags.tag'),
        ),
    ]
