# Generated by Django 4.0.3 on 2022-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
